In [58]:
samples = [True,False,False]
all(samples)
import numpy as np
import pandas as pd
samples = np.array(['사과','바나나','딸기','사과','오렌지','바나나','바나나'])
df = pd.DataFrame(samples,columns=['과일'])
df['과일'].mode()

0    바나나
Name: 과일, dtype: object

In [59]:
# 결측치 탐지
import pandas as pd
import numpy as np

df = pd.read_csv(r'data\messy_data.csv')
print(f'원본 데이터 shape : { df.shape}')
print(f'결측치 개수 : { df.isnull().sum().sum()}')
print('='*50)
print(f'결측치 비율 : { df.isnull().mean().round(2)}')
print(f'결측치가 포함된 행의개수 : { df.isnull().any(axis=1).sum()}')

원본 데이터 shape : (112, 6)
결측치 개수 : 27
==================================================
결측치 비율 : id            0.00
name          0.00
age           0.06
salary        0.05
score         0.10
department    0.03
dtype: float64
결측치가 포함된 행의개수 : 25

In [60]:
df.tail().isnull().astype(int)

     id  name  age  salary  score  department
107   0     0    0       0      1           0
108   0     0    0       0      0           0
109   0     0    0       0      0           0
110   0     0    0       0      0           0
111   0     0    0       0      0           0

In [61]:
# 결측치 삭제
# 결측치가 있는 행만 출력
df[df.isna().any(axis=1)]
# 결측치가 하나라도 있는 행을 삭제
df_drop_any = df.dropna(how='any')
# 모든 값이 NaN인 행만 삭제
df_drop_all = df.dropna(how='all')
len(df_drop_all) - len(df)
# 특정컬럼기준 삭제
df.dropna(subset=['age','salary'])
# thresh - 최소 N개 유효값이 있어야 보존
df_drop_thresh = df.dropna(thresh=4)
df_drop_thresh[df_drop_thresh.isna().any(axis=1)]

     id     name    age   salary  score department
5     6   user_6    NaN  58956.0  96.54         개발
6     7   user_7  300.0      NaN    NaN         영업
8     9   user_9   40.0  72034.0    NaN         개발
12   13  user_13   53.0  56868.0    NaN         영업
14   15  user_15    NaN  54903.0  88.78         인사
15   16  user_16   20.0  48783.0    NaN         인사
21   22  user_22   55.0      NaN  94.01        마케팅
29   30  user_30   44.0      NaN   1.81        마케팅
35   36  user_36   61.0  45258.0    NaN         재무
40   41  user_41   26.0  38389.0    NaN         개발
41   42  user_42   56.0  44603.0    NaN         개발
47   48  user_48   43.0  42400.0  66.89        NaN
54   55  user_55   25.0  54520.0  99.46        NaN
58   59  user_59   34.0      NaN  74.77         인사
59   60  user_60   53.0  37663.0    NaN         재무
62   63  user_63   19.0  43374.0  57.23        NaN
65   66  user_66    NaN  28603.0    NaN         개발
68   69  user_69   43.0      NaN  48.53         영업
72   73  user_73   53.0      NaN  93.00         재무
80   81  user_81   38.0  50421.0    NaN         영업
81   82  user_82    NaN  32044.0  13.66         재무
83   84  user_84    NaN  56472.0  55.28         인사
84   85  user_85    NaN  33549.0  29.65         개발
100  84  user_84    NaN  56472.0  55.28         인사
107  81  user_81   38.0  50421.0    NaN         영업

In [66]:
# 결측치 대치
# 고정값으로 대치
df_fill_zero =  df.copy()
temp = df_fill_zero.isna().any()
print(temp[temp.values].index)
df_fill_zero['score'].fillna( df_fill_zero['score'].median() )
dept_mode = df_fill_zero['department'].mode()[0]
df_fill_zero['age'].bfill()

Index(['age', 'salary', 'score', 'department'], dtype='object')

0      56.0
1      46.0
2      32.0
3      60.0
4      25.0
       ...
107    38.0
108    28.0
109    56.0
110    41.0
111    59.0
Name: age, Length: 112, dtype: float64

In [80]:
import pandas as pd
import numpy as np
df = pd.read_csv('data/messy_data.csv')
df['score'].interpolate(method='polynomial',order=3)

0       17.500000
1       98.220000
2       51.660000
3       26.080000
4       99.630000
          ...
107    118.594571
108     70.040000
109     17.500000
110     66.900000
111     49.390000
Name: score, Length: 112, dtype: float64

In [86]:
import pandas as pd
import numpy as np
from glob import glob
df = pd.read_csv(glob('../data/*.csv')[1],low_memory=False)

In [98]:
len(df.columns)

39