In [13]:
import pandas as pd
from glob import glob

filepath = 'data/*.csv'
files = glob(filepath)
print(files[8])
df = pd.read_csv(files[8])
df.head()

data\소상공인시장진흥공단_상가(상권)정보_서울_202512.csv

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA010120220804265295,60계치킨암사,선사점,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1174010700105020004015779,암사동정웅빌딩,서울특별시 강동구 상암로3길 8,134877,5241,NaN,1,NaN,127.126859,37.550810
1,MA010120220809658173,성심인력공사,NaN,N1,시설관리·임대,N104,고용 알선,N10401,고용 알선업,N75110,...,1117010700100430059022991,NaN,서울특별시 용산구 한강대로 385,140821,4320,NaN,NaN,NaN,126.972240,37.552803
2,MA010120220808205276,칸토빈,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1150010800200200002002536,공항시장역,서울특별시 강서구 방화동로 30,157240,7619,NaN,1,NaN,126.810493,37.563548
3,MA010120220804370987,까치노래연습장,NaN,R1,예술·스포츠,R104,유원지·오락,R10407,노래방,R91223,...,1135010500101690179002482,NaN,서울특별시 노원구 한글비석로23길 2,139815,1682,NaN,NaN,NaN,127.071218,37.660715
4,MA010120220810170381,금빛주얼리,NaN,G2,소매,G217,시계·귀금속 소매,G21701,시계/귀금속 소매업,G47830,...,1111015100100880001000001,종로주얼리타운,서울특별시 종로구 돈화문로10길 2,110370,3138,NaN,1,NaN,126.991861,37.572331

In [20]:
df2 = df.drop('상가업소번호',axis=1)
df2.columns

Index(['상호명', '지점명', '상권업종대분류코드', '상권업종대분류명', '상권업종중분류코드', '상권업종중분류명',
       '상권업종소분류코드', '상권업종소분류명', '표준산업분류코드', '표준산업분류명', '시도코드', '시도명', '시군구코드',
       '시군구명', '행정동코드', '행정동명', '법정동코드', '법정동명', '지번코드', '대지구분코드', '대지구분명',
       '지번본번지', '지번부번지', '지번주소', '도로명코드', '도로명', '건물본번지', '건물부번지', '건물관리번호',
       '건물명', '도로명주소', '구우편번호', '신우편번호', '동정보', '층정보', '호정보', '경도', '위도'],
      dtype='object')

In [ ]:
result = []
for cname in df2.columns:
    if '코드' in cname:
        result.append(cname)

result

In [32]:
result = [ cname  for cname in df2.columns if '코드' in cname] + ['지번본번지',	'지번부번지',	'지번주소','건물관리번호']
result += ['도로명',	'건물본번지',	'건물부번지','건물명','구우편번호',	'신우편번호',	'동정보'	,'층정보',	'호정보']
df3 = df2.drop(result,axis=1)
df3.head()

,상호명,지점명,상권업종대분류명,상권업종중분류명,상권업종소분류명,표준산업분류명,시도명,시군구명,행정동명,법정동명,대지구분명,도로명주소,경도,위도
0,60계치킨암사,선사점,음식,기타 간이,치킨,치킨 전문점,서울특별시,강동구,암사2동,암사동,대지,서울특별시 강동구 상암로3길 8,127.126859,37.550810
1,성심인력공사,NaN,시설관리·임대,고용 알선,고용 알선업,고용 알선업,서울특별시,용산구,남영동,동자동,대지,서울특별시 용산구 한강대로 385,126.972240,37.552803
2,칸토빈,NaN,음식,비알코올,카페,커피 전문점,서울특별시,강서구,공항동,공항동,산,서울특별시 강서구 방화동로 30,126.810493,37.563548
3,까치노래연습장,NaN,예술·스포츠,유원지·오락,노래방,노래 연습장 운영업,서울특별시,노원구,상계5동,상계동,대지,서울특별시 노원구 한글비석로23길 2,127.071218,37.660715
4,금빛주얼리,NaN,소매,시계·귀금속 소매,시계/귀금속 소매업,시계 및 귀금속 소매업,서울특별시,종로구,종로1.2.3.4가동,묘동,대지,서울특별시 종로구 돈화문로10길 2,126.991861,37.572331

In [31]:
df2.loc[:, '지번본번지':]

,지번본번지,지번부번지,지번주소,도로명코드,도로명,건물본번지,건물부번지,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,502.0,4.0,서울특별시 강동구 암사동 502-4,117404172130,서울특별시 강동구 상암로3길,8.0,NaN,1174010700105020004015779,암사동정웅빌딩,서울특별시 강동구 상암로3길 8,134877,5241,NaN,1,NaN,127.126859,37.550810
1,43.0,59.0,서울특별시 용산구 동자동 43-59,111702005005,서울특별시 용산구 한강대로,385.0,NaN,1117010700100430059022991,NaN,서울특별시 용산구 한강대로 385,140821,4320,NaN,NaN,NaN,126.972240,37.552803
2,20.0,2.0,서울특별시 강서구 공항동 산 20-2,115003115005,서울특별시 강서구 방화동로,30.0,NaN,1150010800200200002002536,공항시장역,서울특별시 강서구 방화동로 30,157240,7619,NaN,1,NaN,126.810493,37.563548
3,169.0,179.0,서울특별시 노원구 상계동 169-179,113504130395,서울특별시 노원구 한글비석로23길,2.0,NaN,1135010500101690179002482,NaN,서울특별시 노원구 한글비석로23길 2,139815,1682,NaN,NaN,NaN,127.071218,37.660715
4,88.0,1.0,서울특별시 종로구 묘동 88-1,111104100049,서울특별시 종로구 돈화문로10길,2.0,NaN,1111015100100880001000001,종로주얼리타운,서울특별시 종로구 돈화문로10길 2,110370,3138,NaN,1,NaN,126.991861,37.572331
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534973,19.0,9.0,서울특별시 송파구 잠실동 19-9,117103123023,서울특별시 송파구 올림픽로,119.0,NaN,1171010100100190009000001,NaN,서울특별시 송파구 올림픽로 119,138908,5501,NaN,NaN,NaN,127.084186,37.512087
534974,11.0,10.0,서울특별시 광진구 화양동 11-10,112154112198,서울특별시 광진구 동일로24길,101.0,NaN,1121510700100110010016699,NaN,서울특별시 광진구 동일로24길 101,143914,5016,NaN,NaN,NaN,127.070563,37.542406
534975,98.0,3.0,서울특별시 동대문구 장안동 98-3,112304115178,서울특별시 동대문구 사가정로25길,21.0,NaN,1123010600100980004014467,NaN,서울특별시 동대문구 사가정로25길 21,130835,2516,NaN,NaN,NaN,127.070371,37.579807
534976,356.0,7.0,서울특별시 마포구 상수동 356-7,114403113023,서울특별시 마포구 토정로,130.0,NaN,1144011500103560007009599,NaN,서울특별시 마포구 토정로 130,121829,4081,NaN,NaN,NaN,126.925497,37.545062
534977,127.0,1.0,서울특별시 중구 오장동 127-1,111404103109,서울특별시 중구 동호로33길,24.0,NaN,1114015400101270001016093,NaN,서울특별시 중구 동호로33길 24,100310,4547,NaN,NaN,NaN,127.000860,37.565655