In [13]:
import pandas as pd
from glob import glob

filepath = 'data/*.csv'
files = glob(filepath)
print(files[8])
df = pd.read_csv(files[8])
df.head()

data\소상공인시장진흥공단_상가(상권)정보_서울_202512.csv

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA010120220804265295,60계치킨암사,선사점,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1174010700105020004015779,암사동정웅빌딩,서울특별시 강동구 상암로3길 8,134877,5241,NaN,1,NaN,127.126859,37.550810
1,MA010120220809658173,성심인력공사,NaN,N1,시설관리·임대,N104,고용 알선,N10401,고용 알선업,N75110,...,1117010700100430059022991,NaN,서울특별시 용산구 한강대로 385,140821,4320,NaN,NaN,NaN,126.972240,37.552803
2,MA010120220808205276,칸토빈,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1150010800200200002002536,공항시장역,서울특별시 강서구 방화동로 30,157240,7619,NaN,1,NaN,126.810493,37.563548
3,MA010120220804370987,까치노래연습장,NaN,R1,예술·스포츠,R104,유원지·오락,R10407,노래방,R91223,...,1135010500101690179002482,NaN,서울특별시 노원구 한글비석로23길 2,139815,1682,NaN,NaN,NaN,127.071218,37.660715
4,MA010120220810170381,금빛주얼리,NaN,G2,소매,G217,시계·귀금속 소매,G21701,시계/귀금속 소매업,G47830,...,1111015100100880001000001,종로주얼리타운,서울특별시 종로구 돈화문로10길 2,110370,3138,NaN,1,NaN,126.991861,37.572331

In [20]:
df2 = df.drop('상가업소번호',axis=1)
df2.columns

Index(['상호명', '지점명', '상권업종대분류코드', '상권업종대분류명', '상권업종중분류코드', '상권업종중분류명',
       '상권업종소분류코드', '상권업종소분류명', '표준산업분류코드', '표준산업분류명', '시도코드', '시도명', '시군구코드',
       '시군구명', '행정동코드', '행정동명', '법정동코드', '법정동명', '지번코드', '대지구분코드', '대지구분명',
       '지번본번지', '지번부번지', '지번주소', '도로명코드', '도로명', '건물본번지', '건물부번지', '건물관리번호',
       '건물명', '도로명주소', '구우편번호', '신우편번호', '동정보', '층정보', '호정보', '경도', '위도'],
      dtype='object')

In [ ]:
result = []
for cname in df2.columns:
    if '코드' in cname:
        result.append(cname)

result

In [33]:
result = [ cname  for cname in df2.columns if '코드' in cname] + ['지번본번지',	'지번부번지',	'지번주소','건물관리번호']
result += ['도로명',	'건물본번지',	'건물부번지','건물명','구우편번호',	'신우편번호',	'동정보'	,'층정보',	'호정보']
df3 = df2.drop(result,axis=1)
df3.head(1)

,상호명,지점명,상권업종대분류명,상권업종중분류명,상권업종소분류명,표준산업분류명,시도명,시군구명,행정동명,법정동명,대지구분명,도로명주소,경도,위도
0,60계치킨암사,선사점,음식,기타 간이,치킨,치킨 전문점,서울특별시,강동구,암사2동,암사동,대지,서울특별시 강동구 상암로3길 8,127.126859,37.55081

In [49]:
df3['상권업종소분류명'].value_counts()

상권업종소분류명
백반/한정식           26376
부동산 중개/대리업       25059
카페               21624
경영 컨설팅업          20952
미용실              19913
                 ...
기타 회계 관련 서비스업       30
낚시터 운영업             26
얼음 소매업              23
비디오방                23
캠핑/글램핑              16
Name: count, Length: 247, dtype: int64

In [ ]:
df3[df3['상호명'].str.contains('치킨')]

In [63]:
df3.isna().any(axis=0)

상호명         False
지점명          True
상권업종대분류명    False
상권업종중분류명    False
상권업종소분류명    False
표준산업분류명      True
시도명         False
시군구명        False
행정동명        False
법정동명        False
대지구분명       False
도로명주소       False
경도          False
위도          False
dtype: bool

In [64]:
df3[df3.isna().any(axis=1)]

,상호명,지점명,상권업종대분류명,상권업종중분류명,상권업종소분류명,표준산업분류명,시도명,시군구명,행정동명,법정동명,대지구분명,도로명주소,경도,위도
1,성심인력공사,NaN,시설관리·임대,고용 알선,고용 알선업,고용 알선업,서울특별시,용산구,남영동,동자동,대지,서울특별시 용산구 한강대로 385,126.972240,37.552803
2,칸토빈,NaN,음식,비알코올,카페,커피 전문점,서울특별시,강서구,공항동,공항동,산,서울특별시 강서구 방화동로 30,126.810493,37.563548
3,까치노래연습장,NaN,예술·스포츠,유원지·오락,노래방,노래 연습장 운영업,서울특별시,노원구,상계5동,상계동,대지,서울특별시 노원구 한글비석로23길 2,127.071218,37.660715
4,금빛주얼리,NaN,소매,시계·귀금속 소매,시계/귀금속 소매업,시계 및 귀금속 소매업,서울특별시,종로구,종로1.2.3.4가동,묘동,대지,서울특별시 종로구 돈화문로10길 2,126.991861,37.572331
5,골든공인중개사사무소,NaN,부동산,부동산 서비스,부동산 중개/대리업,부동산 중개 및 대리업,서울특별시,마포구,성산2동,성산동,대지,서울특별시 마포구 월드컵로34길 6,126.903067,37.564570
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534971,오부찌,NaN,음식,한식,백반/한정식,한식 일반 음식점업,서울특별시,송파구,문정2동,문정동,대지,서울특별시 송파구 송파대로 167,127.120755,37.484557
534972,생각과생각사이,NaN,음식,한식,백반/한정식,한식 일반 음식점업,서울특별시,용산구,용산2가동,용산동2가,대지,서울특별시 용산구 신흥로 11,126.986332,37.539624
534973,살림,NaN,소매,기타 상품 소매,그 외 기타 상품 전문 소매업,그 외 기타 분류 안된 상품 전문 소매업,서울특별시,송파구,잠실2동,잠실동,대지,서울특별시 송파구 올림픽로 119,127.084186,37.512087
534975,하루곰탕,NaN,음식,한식,국/탕/찌개류,한식 일반 음식점업,서울특별시,동대문구,장안2동,장안동,대지,서울특별시 동대문구 사가정로25길 21,127.070371,37.579807
534977,에이치아이디자인,NaN,소매,장식품 소매,기념품점,기념품; 관광 민예품 및 장식용품 소매업,서울특별시,중구,광희동,오장동,대지,서울특별시 중구 동호로33길 24,127.000860,37.565655

In [67]:
df4 = df3.drop(columns=['지점명'])
df4.head(1)

,상호명,상권업종대분류명,상권업종중분류명,상권업종소분류명,표준산업분류명,시도명,시군구명,행정동명,법정동명,대지구분명,도로명주소,경도,위도
0,60계치킨암사,음식,기타 간이,치킨,치킨 전문점,서울특별시,강동구,암사2동,암사동,대지,서울특별시 강동구 상암로3길 8,127.126859,37.55081

In [76]:
df4.query('상권업종소분류명 == "치킨" ')

df4[df4['상권업종소분류명'] == '치킨']

,상호명,상권업종대분류명,상권업종중분류명,상권업종소분류명,표준산업분류명,시도명,시군구명,행정동명,법정동명,대지구분명,도로명주소,경도,위도
0,60계치킨암사,음식,기타 간이,치킨,치킨 전문점,서울특별시,강동구,암사2동,암사동,대지,서울특별시 강동구 상암로3길 8,127.126859,37.550810
72,인생닭강정,음식,기타 간이,치킨,간이 음식 포장 판매 전문점,서울특별시,중랑구,망우본동,망우동,대지,서울특별시 중랑구 망우로62길 20,127.097498,37.598194
123,큰집닭강정,음식,기타 간이,치킨,치킨 전문점,서울특별시,동대문구,신설동,용두동,대지,서울특별시 동대문구 천호대로13길 16,127.030078,37.574688
405,비에이치씨제기역점,음식,기타 간이,치킨,치킨 전문점,서울특별시,동대문구,용두동,용두동,대지,서울특별시 동대문구 왕산로26길 23,127.036554,37.577020
435,굽네치킨마포도화점,음식,기타 간이,치킨,치킨 전문점,서울특별시,마포구,도화동,도화동,대지,서울특별시 마포구 도화4길 23,126.951164,37.540885
...,...,...,...,...,...,...,...,...,...,...,...,...,...
534805,황금통닭,음식,기타 간이,치킨,한식 일반 음식점업,서울특별시,중구,신당5동,신당동,대지,서울특별시 중구 퇴계로 426,127.018902,37.565464
534814,1번지통닭,음식,기타 간이,치킨,한식 일반 음식점업,서울특별시,성북구,종암동,종암동,대지,서울특별시 성북구 종암로24가길 16,127.035852,37.600743
534869,지코바문정,음식,기타 간이,치킨,한식 일반 음식점업,서울특별시,송파구,장지동,문정동,대지,서울특별시 송파구 새말로 171,127.131770,37.485798
534871,처갓집양념치킨북,음식,기타 간이,치킨,한식 일반 음식점업,서울특별시,서대문구,충현동,충정로3가,대지,서울특별시 서대문구 경기대로9길 81,126.959705,37.564423
534931,60계치킨서울우,음식,기타 간이,치킨,한식 일반 음식점업,서울특별시,양천구,신월5동,신월동,대지,서울특별시 양천구 화곡로13길 13,126.833453,37.540553

In [90]:
# df4[df4['상권업종소분류명']=='치킨']['상권업종소분류명']
df4.loc[ df4['상권업종소분류명']=='치킨'  , '상권업종소분류명' ] = '통닭'

In [98]:
df4.loc[df4['상권업종소분류명']=='통닭', ['상호명','상권업종대분류명']] = ['통닭집','chiken']

In [99]:
df4[df4['상권업종소분류명']=='통닭']

,상호명,상권업종대분류명,상권업종중분류명,상권업종소분류명,표준산업분류명,시도명,시군구명,행정동명,법정동명,대지구분명,도로명주소,경도,위도
0,통닭집,chiken,기타 간이,통닭,치킨 전문점,서울특별시,강동구,암사2동,암사동,대지,서울특별시 강동구 상암로3길 8,127.126859,37.550810
72,통닭집,chiken,기타 간이,통닭,간이 음식 포장 판매 전문점,서울특별시,중랑구,망우본동,망우동,대지,서울특별시 중랑구 망우로62길 20,127.097498,37.598194
123,통닭집,chiken,기타 간이,통닭,치킨 전문점,서울특별시,동대문구,신설동,용두동,대지,서울특별시 동대문구 천호대로13길 16,127.030078,37.574688
405,통닭집,chiken,기타 간이,통닭,치킨 전문점,서울특별시,동대문구,용두동,용두동,대지,서울특별시 동대문구 왕산로26길 23,127.036554,37.577020
435,통닭집,chiken,기타 간이,통닭,치킨 전문점,서울특별시,마포구,도화동,도화동,대지,서울특별시 마포구 도화4길 23,126.951164,37.540885
...,...,...,...,...,...,...,...,...,...,...,...,...,...
534805,통닭집,chiken,기타 간이,통닭,한식 일반 음식점업,서울특별시,중구,신당5동,신당동,대지,서울특별시 중구 퇴계로 426,127.018902,37.565464
534814,통닭집,chiken,기타 간이,통닭,한식 일반 음식점업,서울특별시,성북구,종암동,종암동,대지,서울특별시 성북구 종암로24가길 16,127.035852,37.600743
534869,통닭집,chiken,기타 간이,통닭,한식 일반 음식점업,서울특별시,송파구,장지동,문정동,대지,서울특별시 송파구 새말로 171,127.131770,37.485798
534871,통닭집,chiken,기타 간이,통닭,한식 일반 음식점업,서울특별시,서대문구,충현동,충정로3가,대지,서울특별시 서대문구 경기대로9길 81,126.959705,37.564423
534931,통닭집,chiken,기타 간이,통닭,한식 일반 음식점업,서울특별시,양천구,신월5동,신월동,대지,서울특별시 양천구 화곡로13길 13,126.833453,37.540553

In [108]:
import numpy as np
import pandas as pd
data = {'age' : np.random.randint(1,100,50) }
df = pd.DataFrame(data)
pd.cut(df['age'],bins=3,labels=['young','moddle','old'])
df['lable'] = pd.cut(df['age'],bins=3,labels=['young','moddle','old'])
df

    age   lable
0    84     old
1    54  moddle
2    54  moddle
3    26   young
4    33   young
5    37  moddle
6    78     old
7    95     old
8    60  moddle
9    25   young
10   44  moddle
11   82     old
12   93     old
13   37  moddle
14   31   young
15   23   young
16   47  moddle
17   40  moddle
18   95     old
19   90     old
20   98     old
21   58  moddle
22   65  moddle
23   40  moddle
24   20   young
25   69     old
26    5   young
27    4   young
28   67     old
29    4   young
30    4   young
31   20   young
32    7   young
33    6   young
34   52  moddle
35   18   young
36   52  moddle
37   80     old
38   44  moddle
39   53  moddle
40   76     old
41   48  moddle
42   88     old
43   15   young
44   98     old
45    2   young
46   24   young
47   64  moddle
48   93     old
49   68     old

In [ ]:
import numpy as np
import pandas as pd
data = {'age' : np.random.randint(1,100,50) }
df = pd.DataFrame(data)
df['lable'] = pd.qcut(df['age'], q=4, labels=['Q1', 'Q2', 'Q3', 'Q4'])
df

In [ ]:
df = pd.DataFrame()
df['date'] = pd.date_range('2026-01-01', periods=150, freq='D')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    150 non-null    datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 1.3 KB

In [ ]:
import pandas as pd
from glob import glob

filepath = 'data/*.csv'
files = glob(filepath)
print(files[-1])
df = pd.read_csv(files[-1])
df.head()
# 결측치 확인 처리(삭제또는 대처)
# 상호명에 '커피'가 포함된 데이터를 별도의 변수 df2에 저장하고
# 출력

data\소상공인시장진흥공단_상가(상권)정보_충북_202512.csv
루트커피
강내염소탕
큰솔공인중개사사무소
별이와콩이
영렘브란트미술학원
한국종이접기협회오송지회꿈창작연구소
파랑새알뜰매장
파파머리방
미오름
한솔스크린골프
신정골전통뼈해장국
와이파이수학학원
늘푸른사진관
두리연치과의원
압구정봉구비어
삼성365정형외과의원
오뚜기농수산물
생각키움+
증평꽃화원
김성철웰빙라이프
청주약국
탑팀키즈짐
증평·내수밧데리할인점
인삼피부관리실
맥스양념치킨호프
한국타이어조령
금강디자인2
진달래피부관리
나비속눈썹염색샵
카페150
제이뷰
남성커트실
고기뜨는집
부광식품
써니노래연습장
안동한우곱창
제비랑일번지
훈춘양꼬치
곰팡이헌터
슐레
시대상회
진천가나렌탈
효드림
머리깍쟁이
중원자동차공업사
행운떡집
다문화카페아오바바협동조합
성호전기
덕성건재철물
스타렌트카음성영업소주
김민영미용실
성우네찐빵
미니스톱
에이치알
미쓰나
찰스리헤어테크북문점
제천특수열쇠
산남대우푸르지오공인중개사사무소
경성종합설비
교차로공인중개사무소
맥퀸스
곰바위식당
포낙보청기
모텔허브
보은철물전기조명
아이나라키즈파크
계곡의아침
데코청주NC점
린헤어아트
미가순대
숀리합숙캠프
더캠프PC방
술퍼마켓포차
시애틀라이브
줌마크린
일번지순대국
쿠스키친
버니블루제천
삼성간판광고
밝은세상의원
비에이치씨치킨
만추가경
하이벳수산충북
가온푸드셀트리온제약점
태진종합상사
한국산학혁신전략연구소
디자인제이씨카울
라마다스크린골프
랑성유황오리
삼영지물
휴일엔
괴산증평축산업협동조합
오복원조칼국수
구독
거성
서울칼라현상소
카롱쇼콜라
갤러리구제보세
카독크서부검사정비
공주얼큰이칼국수.쭈꾸미
이원식당
초가정
진성인력직업소개소
엠버
평화모텔
충북기자협회
목계반점
뽑기나라
정통의정부부대찌게
에스티코
동부불고기
무극편의마트
황금소나무
청일윤업사
설미용실
풀하우스민박
그로브러닝서충주어학원
계룡공인중개사사무소
현진공인중개사사무소
삼보멀티랜드
건기써비스
희망철물건재공구
오송효성공인중개사사무소
스케쳐스청주점
대성전기
진솔텔레콤
감초당한약방
창신한약방
금메달옷수선
영패션
계절이야기
금빛공인중개사사무소
한라공인중개사사무소
베트남식품
황소고집
평생나눔사업협동조합
폼맨즈라운지
우진상회
좋은클린
은성공인중개사사무소
속초실비집
청계인테리어광고
엠비시뮤직타운
신한공인중개사사무소
코리아
산호모텔
단양삼시세끼
민Art
청주TBJ
옛날주막집
유승세탁소
제천가스충전소
떡하니
컵오커피
천생연분
충남오토바이
수목정
채플린노래연습장
영우팬시
본도시락
행복푸드한식뷔페
세븐일레븐충북
휴먼케어필라테스
국수랑족발이랑
황해반점
목민정한의원
인천식당
통일공인중개사사무소
도기상회
미림보석
이곳
호암낚시터
강바다
라온힐조스터디카페
쭈꾸미아줌마
오케이마트
천궁
어라이스
간판나라
샤넬
똥광노래타운
토박스
글로벌파트너
아메리카노라운지
책읽는다락방
태양슈퍼
이끌림네일
프라임Ⅱ
신흥상회
휘트니스오름
능암
브띠아헤어피부갤러리
아름다운세상
햇살아래관광농원
조선청주점
우리들약국
강남댄스스포츠학원
쾌단란주점
금릉스크린매점
건방진김밥
충주농협호암행복지점로컬푸드직매장
헤어까미
향기톡톡
금잔디미술학원
마당식당
프로마치
스타이발관
샘물정수기
유화정
이지케어
은성
양청골흑염소
당골
보물섬
육수당청주북문로점
아리아카페
다예헤어갤러리
청춘국물닭발
세븐청주주성센터점
검정고무신
피오피
꼼빠니아
SK텔레콤
상당문구사
금호타이어프로내덕점
화담
감탄
네일#
월악산촌생태
원뜰
우리이용원
해오름여행사
세계로약국
두찜1호점
홍두꺼비충북
키네틱리쿠르팅
아나덴슈가링왁싱청주
미모아종합화장품
지인
헤어포유
일노베카페
신항도복집
야미야미
썬하우징
봉틀스토리
웰빙노래연습장
청담이엘의원
유정
김애자선물코너
사랑채
더미인's
학사공인중개사사무소
어반
한라낚시
청춘
창성
카페37
청수미용실
터전공인중개사사무소
햇살머믄꼬마김밥
여은혜헤어
별난식당
칼슨그레이시충북총본관오창주짓수
씨앤제이에스
태평양가스
사계절
태양식당
신미래공인중개사사무소
모닝마트
행복공인중개사사무소
오딧세이호텔
인터넷공인중개사무소
동월
영일상사
샬롬헤어샵
하나떡방앗간
이마트24오송골드리치점
빽다방청주오송점
힐타이
아로이아로이
수곡먹거리
명륜진사갈비청주오송점
누리급수
자연누리개발
충주U외과의원
에뎀픽쳐스
알앤비
태양정보테크
푸른가정의학과의원
KP세탁소
미스터브리즈충북오송점
청춘치킨
뉴판다김밥
케이팝노래뮤비
우영임전단광고기획
파인
가죽공방손
온네일
주성건강약국
임플라인치과의원
손오공직화족발/얼음골냉면
나눔식당
엄마닭갈비
대형상사;진천적재함
비와이씨
로뎀당구장
중앙토종족발
중앙전단광고
세탁풍경빨래방
광성공인중개사사무소
물레방아
참사랑약국
CNS축산컨설팅
매곡주유소
달려라빠박이PC방
천지양꼬치
뮤즈의원
목행목욕탕
충북음성혁신구장
김박사면옥
이유영수학원
미성자동차유리상사
천사카랜드정비공업사
리안헤어;이소연미용학원;매지컬화장품
다원헤어
왕당구장
태성디지탈솔루션
상록수공인중개사무소
가마치통닭내수청주점
화원마트
휴대폰맛집
코뚜레골동품
더맨남성컷트
비내섬의아침
홍경백함흥냉면오창
이쉐프참치
오가닉메이커협동조합자연드림식탁
네네치킨
강남부동산컨설팅
라이
리젠트여관
제이시스템냉열
황금공인중개사사무소
팝스광고인테리어
솔져치킨
서울왕만두
국영에너지
HS엔지니어링
수커피&호프
교현카종합상사
푸른농장태양광
한일유리사
류
장가네뼈나라
찾아줘홈즈공인중개사사무소
벌교꼬막정식
토마토공인중개사사무소
참마트
일심장어
영창피아노
대웅약국
우박집
치킨플러스충주산척점
글로벌문화센터
뷰티인플레이스
카페;사계
백봉휴게소
씨유음성봉현
3POPPC방
인삼골순대
이마트충주점제임스딘
의료재단병원
동해건강원
엠제이댄스아카데미
바람꽃호암직동점
헤어짱
시골밥상
혜광의료재단
랑성발효원
아시아마켓
칠갑산
착한컷트
도화마라탕
나비네일
11월의아뜰리에
학교법인서원학원
경성만두요리
문화축산물식당
삼봉
메이49-10
현대오일뱅크㈜직영서원경주유소
더울림
아싸포차
취하는밤
통불
맹동카센타
혜화동칼국수
현우사
컴퓨터랜드
리본메이크업샵
대게마트
기술단주
김씨팩토리
신우시스템비계
형제종합인테리어
대박호프
신광기술사
자인시스템
구병산골가든
지구부동산컨설팅
롯데상회
태율회계법인
상원사건강원
장수건강원
자연공인중개사
수염색방
태일전력기술단
카페샌디에고
명공사
월악산펜션
블루필터
청주식당
디바모텔
소풍
삼양밧데리
진미떡방앗간
열정국밥
충청미용상사
우리문구사
크라라
백삼환경기술
표가네명품순두부
그옛날만두찐빵장터
닥터보일러
삼익종합화장품
화이트전문피부관리
열린약국
메밀음식묵사발
창고형의류할인매장
바른정육점
아리랑영상사진관
목화매점
장수정
캘빈클라인언더웨어
마스터잉글리쉬
위더스엔지니어링
칠칠이용원
현대철물
젬마살롱
암행어사가든
현대유압호스
쓰리픽
짜장나라
하루과일주스앤디저트가경
일호파크목욕탕
케이스타일헤어
공인회계사세무사정재훈회계사무소
세븐충북옥천가화점
돈필피파
샤론오브스톤
용산철물
피자나라치킨공주
희망식당
피자인
힐링미용실
원카피사
강릉교동짬뽕
가원
청정돼지국내산삼겹살
아름사
덕이식당
유어빈티지
법무사허성봉사무소
청기와해장국
법무사이덕상사무소
우암우정점
메이플
신대박부속구이
신축산
그린라이프스타일
금가카서비스
산골조경주
충청북도자치연수원
우리건설산업
민속떡집
다옴솔루션
본가
금왕
이엠아이엔씨
다원
서해바다해물찜
직지세무법인동
시장약국
GS25제천바이오타운
디쉐어에이닷청주개신지점
배스킨라빈스청주가경파크점
괴강휴게소
옥천초량순대
토담
단골식당
자모식당
엄지마라탕
슬기로운부동산중개사무소
별장가든
모델리즘
엘티엘
삼일테크
에스앤피ENG
이리오너라
전주대가콩나물국밥연수
파브리카
MK
하루의식탁
삼성마트
한국식문화교육협회
떡앤디저트
닭발용암점
민물촌
비네릭
홍선개발주
중앙셀프세차장
하얀집
전국소파제작수리
사평리휴게소
안셈
중원산업개발주
더지니어스학원
선녀와나무꾼
안남부동산컨설팅
대원OA정보
동경카센타
청주컴퓨터수리
원마루터
타이어&훨얼라이먼트
로랜드치킨
프리즘헤어솔루션
남정골
리더스21
크린토피아청주용암
새연산업
허리우드당구장
금강가든
오&소
보니또메이크업
금성인력
금강나루터식당
머리이야기
김진권라이브까페
선경공업사
송이다방
연동슈퍼
완면집
진강정청주
충북세종항운노동조합
영동중앙가스
비엔나미용실
수룡상회
우주꽃방
수향식육점
그린파크
스타공인중개사사무소
불로초건강원
아리스
르노자동차서비스코너제천점
명진
독일보청기
청담에스테틱
네일바이썬
대국전자
취향
잉크피아
쌍방울단양점
한국종합전자
옥천과일
착한미용실
한농마을
역전철물
북경
텍스타운
디바헤어샵
해와달주유소
명화가방
은성인력직업소개소
피앤디푸드
불닭발땡초동대문엽기떡볶이충북
반함뷰티
엠에이치모터스
가인상사
노란푸드
엠앤
헬로컴퍼니
산에산양
달마설렁탕숯불갈비연수
눈빛
형제상포
주성종합약국
주영스킨케어
엄마손밥상청주청남시니어클럽
제일고시원
신신볼링장
가나문화사
쌍곡금호쉼터
법무사지태흥사무소
쎄븐미용실
청주제이킥무에타이주짓수디펜스랩
돼지띠
월정손칼국수
청천건강원
모어엔
탑엔지니어링
트윈자동차공업사
미성광고
아모르
로또노래연습장
짱만두
오미뜰류가네
혜리중국식품점
영동점현대자동차
커피철학
케이팝스타코인노래연습장
새행운이발관
개와고양이
한국건강원
휴먼월드
충주기아상사
청주조개구이무한리필
수제햄고래부대찌개오창
마이요거트립청주점
심가네동죽칼국수
청풍명월
서주희헤어갤러리
서울가스충전소
청하공영
남청원현대서비스
씨유음성디씨점;워시팡팡무인셀프빨래방음성디씨점
섬레스토랑
미르시스템충북센터
한내슈퍼
다연닭갈비순두부왕십리곱창볶음
신광상회
와이솔루션
봄세탁소
세운
꿈나라노래연습장
네네치킨앤봉구스밥버거용암
사계절고깃집
보령물산주
장성주유소
요가리움아카데미
푸른솔휴먼뱅크
금관원조식당
두진공인중개사사무소
법무사윤종률사무소
송두점현대자동차
50년전통칼국수·삼계탕
맛나감자탕
쌈성화점
카팩트
청향가든
경주이용원
미르테크OA
항아리보쌈
꽁꽁냠냠목행참
청주에폭시인쇄협동조합
우성식당
피앤씨정보통신
청주현대자동차
뷰티살롱늘봄
반씨상회
이오일SHOP
내차꾸미기
포차사랑
한성세탁소
스시진
오송랜드부동산공인중개사사무소
신세계패션
BHC서충주
한성수출포장
백옥미용실
모아옷수선
사계절동기와
산수가든
미립
쵸이케이크
만복가든
머리예뿜헤어샾
에스엠스포츠
백송식당
힐링마사지
달콤달달
신한천식당
대영공업사
행복양행
마린시티
새벽공인중개사사무소
97요리하는주방
풍년가식당
순희네
골드닉스
김기석세무회계사무소
김칠복커피
국제
불타는구공탄
생기365
정원이아름다운집
소나타노래연습장
평화로운집
헤라모텔
삼성가스
제이에스컴퍼니
단양아리곳간
파리바게뜨청주강서점
민아식당
요기
동남청미르공인중개사사무소
크린시아
셉템버나인커피로스터
테라스에별이뜨면
신한산업개발
별헤는밤
찬스
인천세탁소
예당한의원
하루비어
최가네
대륙열쇠
삼천리자전거
진짜루
단성머리방
하늘신소재주
포인트모텔
대영잡화
구산동농다리
원조설악추어탕
헤어블리스
서희애드
메탈리코아트
제이제이스크린골프
홈마켓
뽑다방
신해물퓨전포차
벅스노래연습장
톡스앤필의원
블루페페웰메이드
삼보정갈비
동방생고기정육점식당
펜션놀스페이스
주덕마트
디모벌룬
글로리
태웅
1.2.3건강원
방가삼대얼큰한뼈해장국
늘수제돈까스
청산숯불구이
고향반점
신동이발
희락
자이나라공인중개사사무소
대복떡집
한나스토리
멕시칸치킨호프
박신영헤어샵
돈산개발
지우라이프
라라약국
홍익축산
스마일화분
메가안경콘택트
그린공부방2관학원
팡스팡스
청주고속터미널
디자인앨리아이스365
찐구제샵
진쥬얼리
바다활어횟집
디자인이슈
이정희헤어카페
단양철물
현정이네머리방
송미홈디자인
지에스25단양소선암점
충주호관광선
디올
덕일개발
인생파스타
남다른감자탕
힐링스파수
중국성
스타일산다헤어샵
행정사김경우사무소
웨딩S&메이크업하우스
은상식당
스피드카
트라이모충점
케이에스지
아름나
수노래연습장
선진T&C
리틀피아니스트음악학원
다래다방
징기스칸치킨
청주옻닭
태공낚시슈퍼
파리바게뜨괴산점
중앙토탈O.A
들꽃
메가엠지씨커피청주
한끼밥상
신척골프랜드
미라주호프
일호행정사
시원한공인중개사사무소
제일철물
청원부동산
69춘천닭갈비
21세기자동차부분정비공업사
영동열쇠
홀맨즈헤어
비플레인
뉴한일사
건건이
엘지종합설비보일러
컴포즈커피충주
단양두산활공장
부영이용원
이상약국
모란국시
해든약국
안경시티
순두부연마루
무지개
가족노래연습장
쉬즈베이글사창점
신화종합정비
쉬는시간
하나로약국
LBA조남정공인중개사사무소
의림지장어촌
영오토바이
간이역
우림컴퍼니
고향토종순대
망고노래연습장
피아노숲음악학원
헤어아티스트
씨엔에이
중원모터스
세움필라테스
토종집
아가방에뜨와
유한산업
덕동달구지펜션
양지고을
싸다25
컴포즈
위드윈
이화수육계장
추평느티나무가든
티엘에스텔레콤
옥산설렁탕
더싼통신
현대코아스포렉스
버거킹오창
강길따라펜션
폴라리스
딸기
장혜경스킨앤바디
배부른한끼
우정손순두부
봉학골오리
뽀꼬뽀꼬
철통닭갈비비하
빵뜨락베이커리
사르르까까프렌즈
동아마트
멍청이찜식당
양지공인중개사사무소
안경매니져
워시팡팡셀프빨래방충주
신예원닭강정앤아이스크림
사람이그리운날
새아람약국
동남우미공인중개사사무소
명천
태세
에스비텍
스탠바이짐청주강서점
미니스톱청주내수점
카엔조이모터스
헤어팀771
옐로우플라스틱
GS25금왕터미널
꺽정이육개장
명가하우스웨딩
세븐일레븐영동산업고점
앤에스바이크
비전텔레콤
길모퉁이포장마차
용성중기
일등냉동전자
대한산업보건협회충북산업보건센터
리컴퍼니
아키포럼이오가건축사사무소
다산노래연습장
현죽청전점
파리바게뜨성화
힐링테라피
왕순대집
스타24미니마트
챌린져투어주
꿈너머꿈스콜라스
엔에스이엔지
열매슈퍼
홍미용실
세왕공업사
동진카센타
하마가든
갈채노래연습장
마레클리
중부에너지
엘이오
고기굽는집살강
삼성식당
네일멜로우
시크릿헤어
예쁜폰아트
등대해물포차
장호각
에단크리닝세탁
여우골건강원
동삼농원
명진글로벌
롯데전자청주서비스센터
안경나라
스타남여헬스센타
봉명동능이손칼국수
유향약국
해인네일
고울연
스튜디오은은
스타모텔
오징어에빠진돼지
오토캠프
블랙타이거합기도
레이스카부분정비공업사
도가네
꾸밈새공방
홍명당한약방
지에스은암
김밥세상
프렌즈마켓
국립공원죽령옛고개명품마을영농조합
타이나컨마트
예뻐지는소리
봉이감자탕;칼국수
대림３급공업사
공공당구클럽
자유식당
다락방의불빛
웰컴
백억공인중개사사무소
르미컬렉션
투뿔가마솥곰탕
청주실내풋살센터
우리종합공구
애플노래궁
네일블링
중원마트
해바라기약국
전국노래자랑노래연습장
건우토목이엔씨
고래미장어
헤어스토리
시당
법인편백힘터
토토맛집
퀸
제천식당
속리산호텔
뉴타운투다리뉴타운점
우주광고
아지트카서비스
노붐1
아르떼심리상담센터
로즈와나
맥스라이더
충주의료기
마리앙뜨
하나마트
Wedding백옥당
미니토리
피자마루충주
나그네회집
경기부동산컨설팅
원양상사
대성에어테크
우리할인마트
산성공인중개사사무소
비앤비
효식품
대성할인마트
창성에어컨
재성가방
무쇠돌이김치삼겹살
유명광택
거명합동공인중개사사무소
새한세무회계사무소
꽃스시
석정
더간지
소나무향기
이우철한방누룽지삼계탕
선진에너지
시골식당한정식
로그아웃
꼬마김밥나라
남부축산유통
부흥유통
청년피자
국제모터스
스마트텔레콤
오레시피청주성화점
콕콕로또명당
바른손스팀세차
씨유서청주IC점
진명유통
능촌낙시터
엔터컴퓨터
아델헤어살롱
24퍼센트
불루민박펜션
모드모아
욜로
업소명없음
예성실업염소숯불구이
공간
모든인력
평화공인중개사사무소
엘림전기
새로이크린주
투미
코코까페
삼삼미용용품점
생거진천중장비학원
월송상회
중원렌탈
서충주공인중개사사무소
뽕미촌
국수서리
수일건설엔지니어링
담다푸드
동백세탁소
체인지
미소로
우가
아임터프팅
썬테크
대풍생고기
진주회센타
연홍지업사
제일약국
지에스25청주
경희뷰티
진공인중개사사무소
쌍용자동차상당서비스프라자
환희카정비
에이치앤에이치
단발머리
장비야광고
삼호할인마트
살롱드엘
충청북도바이오씨에스
빈체로
하늘종합물류명성살수차
우리상회
자미온하우스충주대리
제이케이모터스
그리고아트미술학원
웰니스바디
세븐일레븐청주가경
남영상회
태평양주유소
씨유청주복대
강호관합기도
노턴
보련식당
지인컨설팅
한양공인중개사사무소
용산가스
어돈가
참보리촌
삼성전자음성
처갓집양념치킨
단장실
합자회사믿음프라자
부부꼼장어
남부불고기
휴먼솔루션
나이스당구클럽
충주탄금다례문화원
끌어모아
황금룡
시크릿당구장
행복한사진공작소
강우카
이미영
다온푸드
파티수
하얀성모텔
카라
알리바바패션
함에스테틱
연무용학원
이삭토스트주
투썸플레이스청주메가폴리스점
피에스앤티
이혜진동안케어연구소
음성소독방역공사
이화수청주강내점
수헤어
온새미로
세븐일레븐보은속리산점
삼탄슈퍼민박
소이
변호사박남현법률사무소
네오건축사사무소
근대화상회
앤아키건축사사무소
피자구구
서울건재공구
은성식당
경도양꼬치훠궈
금성카
진수성찬
승리셀프세차장
우하주
유진연탄
삼성세무법인
짬뽕하세가경강서점
그림;스킨바디
이오여행사
꽃눈피우다
드림공인중개사사무소
이기성헤어라이프
기똥찬중화반점
천등산박달재
대구막창
명성토탈클린
G통신
소잉피플태양미싱
비즌
용정세탁소
덕산노래궁
한살림청주율량매장
바다별
벧엘냉동
이마트24충주엄정점
이펙트
한국실용음악예술협회
덕산하나
석천정육점식당
대잠리노인회
백마호프
케이엠보광
서울슈퍼
마트열쇠수리점
아인동물의료센터
충북불고기
태화크린
요거프레소
씨유진천성석점
미쿡식당
뉴스타미용실
보은하나이동통신
대광전기
안명순세무회계사무소
김용호세무회계사무소
인기획
이지컨설팅
삼성114부동산투자개발
만물문구서점
한빛통신
수연뷰티
그린마트청과
월악24시슈퍼
법인인삼
사운드뮤직음악학원
효촌숯불생고기
다경바지락칼국수
강남노래뮤비방
수정약국
피아제이
쏭스뷰티크
가마골
야베스상사
인생곱창
숲속의쉼터
명품타바코
신백카센타
금봉이휴게소
시골닭집
민성개발유한책임회사
무지개세탁소
기와집곰탕2017
실버안한방병원
카리스마퀸
진천농다리공인중개사사무소
주전부리제작소
오월의식당
더원공인중개사사무소
형제상회
송이네밥상
신흥산업
루벤스공방
투썸플레이스
우드랩
폭포수펜션
못잊어식당
피스바이피스
풀문3
어울림음악학원
정통합발달센터
수영식당
티아라
초원이엔씨
키건축사사무소
파리바게뜨옥산파크자이
양푼이포차
콩심강제점
짠지마루
국빈식당
온수옥매트라꾸라꾸침대
똥광게임장
금왕의료기
홍이랑
비바체음악학원
슈페리어청주
대림
선진기술단
대림오토바이보은
세종공인중개사사무소
예찬악기
힐튼
스터디카페봄
온정+플러스
커피길
행복모아구내식당행복담은네모점
누리종합건축사사무소
에넥스문화
로얄음향악기사
산성칡냉면
전주명가콩나물국밥
충주돌구이
세운산업
광어두마리17;000원
큐노래연습장
영동모텔
증평공인중개사사무소
참좋은굼벵이곤충농장
보니타에스테틱
지에스25청주폴리텍점
경희쇼핑
염병옥오리탕
옹달샘
상봉주유소
마법의상자
영민카서비스
어반트리
신일사
맛있는식사여기
빌드그린
오딧세이
네일살롱
비에이치씨충북
씨유오창2산업단지
텍사스12바베큐
고향축산물불고기
구도일주유소오송햇살
아이빈뷰티
한일컴퓨터프라자
오송팡팡복권방
부동산스케치합동공인중개사사무소
오더디자인스튜디오
행복마을연구소
슈페이스
옛날가마솥맛집
바르다;네일
한중항공여행사주
K닷컴
동안주유소
구구맥주
대박순대
브레드홈
은하수민박
황실제과
백반/한정식
올가베스트GS25충주공군점
현대경매공인중개사사무소
예가하우징;우리정보통신
대영그릇도매센타
레쓸
요쏘헤어샵
성신과사람들
원조명동칼국수
진천숯불고기
올
도연
부성
태창전기설계사무소주
옛날식당
샤론악세사리판매업
시장불고기
25시
다온헤어
그린이에스
두리두리
티에스바이오
트리안
털보공인중개사사무소
세영공인중개사사무소
더짝게스트하우스
와오양꼬치
현헤어샵
키즈닥터영재학원
원애드컴퍼니
롯데리아청주
신전떡볶이
그린조이
착한초밥
모들펜션
하와이노래연습장
예성파트너스
아관원
윈윈파트너스
구이와국시
대성철물건재
짜장만세
웰니스스킨앤바디
다복회
시카고피자
520클럽
민숙앤수화아트스튜디오
장수식당
보리밭보리밥집
후끈매운양푼갈비찜
휴노츠
슬이네마켓
투다리수안보
일등식당
세븐데이즈슈가왁싱
가자스크린골프
남도한정식
착한양꼬치
킹덤
마리에
박종화공인중개사사무소
나무꾼카페
다담뜰한식뷔페북청주점
강주네반찬가게
골든파크
기성광고
오브밀
노벨시티공인중개사합동사무소
25시해장국
앤유Andyou
아지트
하나애드컴
옥천파맥스약국
벼리기획
고소미견과
휠앤킥청주점
11번가구제천국
청주정상어학원주
한울
조윤식신경과
진천세탁소
앙성엄마손분식
더원사운드
충북장례의전협동조합
새동신약국
서원컴퍼니
워시팡팡셀프빨래방교원대점
서문우동
연로그
카페오늘오송생명점
지엔에스엔지니어링
오픈박스충주
퀸헤어뱅크
미우뷰티
시항골
청풍명월황기찐빵
오디향
대도영지숯불구이
시장철물
벨리걸NC청주점
히든
이랜드월드홈플러스청주점
동서엔지니어링종합건축사사무소
공원카센타
재이디자인
레겐보겐
맑은물식당
청주시시설관리공단
오슬로Ⅱ
진천장터순대
큐피드
드프로방스
실비가
음성축협친환경축산물프라자
인더피트니스
파리바게뜨
물망초
이쌤푸르넷공부방
한마당홍어전문
한국인포네트;탄금골프클럽
블랙컴퍼니
대학로친구분식
더큰여행주
한그루
더고운에스테틱
옛날손만두
예스투어
키스단란주점
투썸플레이스가경파크점
태이빈티지
청주실내테니스장
머리염색
아재카츠
민선희뜨개방
봉방그린유통
한우내장탕
대일부동산
라오비
알씨디스페이스
옥돌찜
오성미용실
노비타청주총판
휴모텔
중국황실정통발관리
보명당
동산주유소매점
MH상사
치킨먹는날
소모리
해성직업소개소
이벤트몰
예술
신애헤어샵
삼태산식당
굽네치킨
에이스마트
봉정식당
한식뷔페
제이블요가
문스안경
김밥천국도전점
진미푸드
향기로운
웰덤치킨본대점
운교랜드
엠제이켐
케이쓰리골프
피씨태그오송점
가자12시뼈해장국
영동마크사，프리챌학생복
르노삼성자동차유리
대광주유소
양군디자인
은혜건강원
오페라하우스
펫스티발
푸른숲펜션
365뽑기
포토포인트
마루헤어샵
라운지
노명호귀금속갤러리
운동화빨래방，OK맑은샘세탁소
국제이발관
바다한접시
대경공인중개사합동사무소
신성공인중개사사무소
윤가네숯불갈비
아지매식당
한복사랑
59년왕대포
안골묵집
변호사홍성배법률사무소
엘지내덕
안경매니져율량
유니나세차장
빠삐
카인외형복원
다원돌솥밥
미가랑공인중개사사무소
백운다례
우주엔지니어링
하이샵
산아래가든
영우인력
순흥마트
밸류어블
이불할인매장
청풍불고기
라온하제공방카페
두구메염소탕
그린제이
단골손칼국수
작은백로
헤어로운
대추나무집
산해원
마산아구찜
체형관리
젊은산꾼들
클린Car
가위여왕
중문떡볶이
다이아
황제스크린골프
이가술집
호암시그니처
단양패러글라이딩
오웨이헤어살롱
논두렁밭두렁
청주공항렌탈
제천가구아울렛
프로원바이크
덕암먹거리분식
오송드림관리
다온스터디카페
은행리낚시터
해나
북단양리조트마트
짜임인테리어장식
달달혀
뽀뚜루까아저씨
경희참한약국
정미용실
그린청소용역
와바앤에어라인
거기솥뚜껑삼겹살
쉬즈미스
애니렌트카
다육식물힐링
청주보부상협동조합
청주밝은미소약국
늑대와여우컴퓨터
터미널카센터세차장
큰손칼국수;보쌈
이룸
마미디저트
금수산가든민박
용산철판동태찜
명성부동산컨설팅
그린목욕탕
수미용실
명장
에덴정
본죽&비빔밥cafe카페
곱이곱다
이부진피부연구소
반달약국
까뜨리네뜨
정코스2공장
트루밸리펜션
텐피부샵
트윈플라워
쿨노래연습장
청주오토월드구내식당
화랑건강원
중앙상회
세종사
보브헤어
왕릉숯불갈비
그린시설정비
엄마손반찬
수안보LPG충전소
신광철물건재
덕성민박
청주KS
마이빌공인중개사사무소
에스티레스토랑
현대명품
서해칼국수
더고운피부관리
월드PC방
대바위주유소
태양미용실
충북보건과학대학교생활체육연수원
Yes공인중개사
남희진헤어
삼성버스터미널
고향순대
착한우
카페지오
세계로안경원
모닝글로리
모요우
신풍미식당
피자콜충주
서울야식
알프스모텔
비비큐
아이힐펜션
영희네수입코너
몸짱얼짱체형관리
바로금강공인중개사사무소
광혜행정사무소
규미네미용실
연
천리안공인중개사사무소
굴다리식당
아트모아
성모이안내과
키즈닥터산남영재학원
스티치
미인머리방
마르까헤어살롱
정원
착한힐링센터
풍경n마린보이
서울복사
지아왁싱
궁뜰펜션식당
우산정사
봄햇살가득한날헤어
멜니짜
구십오도씨
청주자동차운전전문학원
네패스이앤씨
뵈뵈한복
명락
내장탕이백
모이어티
건국우유영동보급소
청원풋살
스마일공인중개사사무소
루시헤어
청해물회
뷰티헤어
유성당구장
나이스렌탈.기획
연풍떡방앗간
기사님식당
두껍집
씨유청주용담동점
큐티체형관리
로또공인중개사사무소
365해장국
에스에스축산유통
드림종합가스
지에스25강서
핸드폰가게
우리식당
춘천일촌닭갈비
통뼈감자탕&고기마당
가야로또복권방
옥천D/C
제이헤어
나래정
역전이용원
장어천왕
동구나무
금왕녹두반계탕
궁중대구왕뽈찜
만금보석
손미용실
에이치피산업관리
헤어본
봉평막국수
토토원
레어템
크린토피아청주용암시티프라디움1차점
데코룸
대림유리
광명종합광고사
자연상사
영광춘
세진신탁컨설팅
여원
하우돈
육천지
청춘카페군청점진천시니어클럽
휠로스테라피
한국에너지
보끄미
한국토지개발평가원
청정마트
바람꽃
탑월드홈파티스스튜디오사직
이너피스카
미원상가
동감푸드
미리내의원
향미각
마암오복식당
수원칼국수
법무사윤정훈사무소
희미용실
중부비즈네트웍스
봉명골순대
이유네일샵
털보관광농원
김경운공인중개사사무소
한국장애경제인협회교육사업단
일조원
초가집대패삼겹살
대구왕뽈찜
세탁풍경
모듬생선찜
까페하너미
부성아이엔씨주
소로지오
신화건축사사무소
성원공인중개사사무소
여유드림셀프빨래방
올리비아로렌영동점
고려자동차정비공장
에덴상회
브이텍
동그라미약국
엠티렌터카충청지점
나래종합상사
둘리밥상
돈티고교현점
호산나
쥬시후레쉬
뉴헤어샵
두두컴퍼니
수내닭꼬치제천장락점
바보형제쭈꾸미
가나건축사사무소
진선미
맘스터치
풀하우스
하얀집민박
김밥나라
연다라
오늘도예쁘다
컴포즈커피충주건국대점
증평대반점
팔공티청주
본블랑제리
한신기획
손가네연탄구이
비트에스케이
양백산패러글라이딩
지에스25진천청암점
노스텔지아
수정수산
그린레이크하우스
서윤푸드
국사봉식당
메가엠지씨커피청주가로수
태영생막창
삼거리식당
튼튼약국
사이만들기
중앙철물점
현풍닭칼국수청주사창점
윤약국
모텔프라자
청년짬뽕
리얼20
가이드공인중개사사무소
우향
참사랑공인중개사사무소
타이월드
옥천수예점
건강미피부미용
건영축산
태양침구
서울김집
더문화
후라이드참잘하는집가경
유미텔레콤
태연미용실
굿타임호프
파티올리
한국파이터클럽분평지관신재환체육관
델타데이타
장원기사식당
퍼스트
에어솔루션
맹꽁이연구소
퍼스트디자인퍼니처
화암리이공삼
진천IC혁신주유소
써니공인중개사사무소
도깨비
삼원세차장
인티모
고등어와밥집
알파
금성제면소
아이앤스튜디오
앨리스공방
웅스시
신가네한식뷔페
보쉬카서비스청주점
글로벌SQ충북본부
중앙주유소
GS25충주뉴건대원룸점
현대충청에뜨와
미스터떡볶이
가오리찜
염촌염소탕
메이무드
해솔
월드이용원
응응스크르청주가경
종로노래연습장
파리바게뜨충북내수점
무심천매운탕
미성명가
대우이용원
책읽는미술관청주송절학원
어댕이
안나가죽공방
명성
맥시칸양념통닭영운체인점
이화순미용실
중앙상사
합자회사오창축산물
정통춘천닭갈비
미성설렁탕
느티울
큰집
미스터피자청주
성수호
범바위뜰아래
CU제천동현
한길공인중개사사무소
뚝배기식당
삼한주
세종에프앤디옥산지점
달밤포차
윤Hairmakeup
강원건재철물
충북파유리
씨유제천세명점
종로부속
프라임펍
맥스스포츠
화곡반점
현건축사사무소
김성식법무사사무소
Cafe1865
충주프라자약국
신용생고기
미연다방
웰바이오
대성광고대행사
카페몰리
단양예그리나펜션
제천공일공
족발신
동화식육식당
혜경미용실
토마토마켓플레이스
샬롬식당
증평BYC
뮤엠영어교습소
현도카센타
남양건강원
근화건축인테리어
동주원
호야헤어샵
이디야청주내덕점
공인회계사윤철한사무소
서문휘트니스클럽
키움부동산중개사무소
넘버25청주성안길점
지에스25오창파크점
한국통신프리텔증평태광
동부주유소
청구디자인
후아유청주
사계절가설재
씨피케이방역
니들수다
충청북도청주의료원
두발자유미용실
다와연
충북하나로유통
디자인시작
좋은약국
카플레이
초이스공인중개사사무소
다은
샤브향청주
명인갈비
벌떼노래궁
더원골프피팅센터
동원인력
북카페문학사
혁이네
하늘샘약국
이레해장국
동부인력
충무러닝센터입석관
호선
원포리
제이엔드에프유통센타
조은그래픽광고
효자농원
백합선물
삼미무선부산경남지사
청산알뜰매장
광택나라
티에스스토리
대원엔지니어링주
중부키넷
혁이네션
영미전기엔지니어링
영동군장애인보호작업장
디저트39제천장락점
태웅리싸이클
아시아
명동왕족
충북상사
건대이모네순대국
스포라이프
미센스
성화우리약국
영웅순대국밥
월성집
타임파크장
에몬스가구청남점
호수노래
제이연테크
공사카써비스
문화원식당
뜨란채공인중개사사무소
불닭발땡초동대문엽기떡볶이
씨스페이스
세기지업사
이지은미용실
제이케이갈비스토리
제이앤케이
반기안경영연구소
더맨즈헤어
루시헤어샵
성모의료기성모복지용구
척산종합철물건재
테일러메이드청주점
쥐눈이콩마을
아이비스P.C
세영이엔씨
쉬크헤어라인
부동산최종호외1명
라블룸
공주칼국수
이류그린농원화물
청주남부아가방
고드미윤곽관리
그랜드부동산컨설팅
가마치통닭
다옹이라옹이네방글농장
탑센스광고기획
그랑프리안경
중앙
와이즈로드
다이써폰
강남스타일노래샵
동량병천순대
킹마트
생약건재약업사
싸모아
데이지파파독
금봉이네
속리산손칼국수
동원홈푸드대영힐스클럽하우스
탑무인텔
토트키즈
데이엔시아
백두대간이엔씨
박재숙미용실
아씨방
대박노래연습장
홍일식품충북북부총판
진국고기국수
교동짬뽕
선프라자컨벤션센터주
장수부동산컨설팅
건배
마블스퀘어
조가정의학과
산남문구픽미픽미아이스
비너스
푸른솔약국
용정당우동
로타리통신
덕성샷시유리공사
본죽&비빔밥충주
구두수선소
터미널슈퍼
커피빈스
씨유청주분평스타일점
가든미용실
설희헤어&피부
쿠로마사
아이스크림세계과자꽁꽁냠냠
그레이스음악학원
투다리봉명현대점
수빈이네미용실
메밀명가막국수
에스앤에이치에너지
대한푸드
직지개발
방곡산길따라펜션민박
와이드앵글
황금당
후니카센터
꿈담공예협동조합
다빈치미술교습소
증평농기계
씨유우암평화점
토담치킨
음성집
골고루부동산공인중개사사무소
에코황토마을
24시전자담배멀티샵
대동집
쁘랭땅세탁소
피카딜리마켓
건축사사무소토탈건축
꿈이자라는뜰
충북보건과학대학교생활체육교육연수원
백작청주점
충북식당
남원추어탕
티나스타일청주점
모답농축산
지호로또
LM시스템
지오라이팅지점점
리베르따
사나포차
3쿠션전용대대구장
형제가구할인마트
메모리성형외과의원
미소연합공인중개사사무소
오송한우명가;정육점
괴산만남의광장휴게소
명당공인중개사
킵핏
와이네일연구소
대원광고산업스카이
용궁해장국
헤비수헤어
DAESAN
레드컴퓨터
제트엘모터스
진천사진관
우림칼국수
고래와인어
어미횟집
지에스25영동대
송림식육식당
통큰
핸드폰파는집
너랑나랑치킨
숲속에놀이터민박
대영페인트
월드휴먼브리지카페파구스충주남부점
세느파크
코스마인
새늘엘앤씨
24시열린슈퍼
한가네삼겹살더해장국
위니아옥천
호텔본
대영알뜰전자
마켓비충주점
할머니손칼국수
아워홈대한제지오송점
사이인터네셔널
아이비클럽
대명주유소
창수네으뜸매운갈비찜
팔영산흑염소
호컨설팅
퍼펙트카오디오
울루루
라임광고기획
네일을그리다
미션(MissionInc.)주
창원막창구이
애니원
산남공인중개사사무소
충청부동산중개
직지버티칼커텐
스네일투어
입시·교과학원
오복이네
기사식당
네오인테리어
별밤뮤직타운
행복광고디자인
임다솜
베스킨라빈스31충북괴산점
나하나사진관
엄마보리밥
피크괴산점
성심이용원
씨케이엔지니어링
슈에뜨
바다양푼이동태탕
눈이부시개
청주본가누룽지삼계탕
베트남쌀국수
마스터매쓰더원교육학원
청해가
제이에이치상사
케이-보자기
마루밥상
작은정원
올클린AllClean
제이아트
청대체육기념사
대륙부동산투자개발
중부복지용구
리플비
우리또래문구
이가자헤어비스충주
대박공인중개사사무소
미닮
풍년골
본가왕족발보쌈
365일폭탄세일
이디야커피
호맥청주
여우야
태경용역
엠에스플랜트
금강상회
나누리약국
남강부동산중개사무소
회인정육식당
다래헌
한빛
휘한당
로즈버드헤어샵
아이프로방스
연세치과의원
청풍식당
태송종합건설
시카고치과의원
민선뷰티헤어
미래사
한국건설시험연구소충북지사
동천칼국수
베이커리와아이스크림할인점
주영
옛날순대국밥
아모레카운셀러
충주농협기업도하나로마트
태양부동산공인중개사사무소
김경미
남산
감골뚝배기해장국
씨유청주사창원룸점
더감
조이아트
진선생헤어클리닉
씨유율량칸타빌4차점
한라장식
인셀덤샤인
메밀뜰
원정노래연습장
통나무2
효자집생고기
남현천부경명상센터
지은미용실
한상모아도시락청주
해맑은꼬마김밥
팜프라자약국
외갓집
우리불교사
산마루
세븐캅
지영옥청국장
백운산업개발
오너가요룸
청남대두메촌
재근이순두부
설화참숯닭갈비
법무법인청녕
예담공인중개사사무소
더쉼카페
평창송어
라이프인플러스공인중개사사무소
데인티스푼조인점
정원숯불갈비
장뜰순대
미샤영동점
베드로슈퍼
금광당
경주떡집
지에스25천년1단지점
네이쳐컬렉션충주점
대소혁신타이어&스마트통신
염색이야기
덕산누리협동조합
청담이상청주
인천어시장
백두산생고기
얀트라요가&필라테스
흙의사람들펜션
농가맛집토박이
숲속카페
가방든남자
금강세차장
삼진마트
일류식당
편한약국
뿅카는생막창
아네모네미용실
두들커피
아침햇쌀떡베이커리
광명
소망슈퍼
굿아시아마트
연풍청정한우
포포
현대기계공업사
OK노래연습장
골드만
옛날순대
중부전자
팍스피씨방
인솔루션
건국우유음성보급소
아랑고고장구
종로발관리
아가방
베다니의상실
어울림공인중개사사무소
명물참쪽갈비
비엠더블유
세븐청주교대점
화끈불끈쭈꾸미
백경
명품노래연습장
도담도담펜션
청수식당
롯데공인중개사사무소
호텔알마
참하나공인중개사사무소
한결;같이
퀼트미랑
오송채움공인중개사사무소
제이엠플러스
레니본테이블
로뎀나무
혜성사진관
헥커컴퓨터
청주외장하드복구USB복구센터
0심이노래연습장
충주미용실
장미숙소머리국밥
둔율올갱이
유승상회
본죽&비빔밥cafe영동점
쉬즈산부인과
다이아필라테스
에스디이포
살롱드에이치
지원건축사사무소
치킨신드롬내수점
지엠모터스
햇살밥상
5_9데이
수정낚시
구루물마을관리사회적협동조합
한마음혜수미용실
코팅몽키즈
세븐일레븐복대타운점
에이핏
헤어지오
한진희미용실
장수장민박
애들나라
네일온유
비에스제천펜션
고래고래가요주점
엄상궁설렁탕
대치탑수학학원
신니부동산컨설팅
보은한방약업사
김현정헤어
충무광고
LS유통
지대루
이든시스템
씨티광고기획
통통분식
가든민박아리랑
아지트헤어
아이비클럽청주점
황금약수탕
용궁중화요리
진천자동차운전전문학원
다사랑치킨피자
정석부동산
향수식자재마트
아카시아식당
명성노래바
대동카바사
샐러드카페초록
증평의류
쌍용자동차오창서비스프라자
블루밸리
디케이스포츠단
최강합기도장
라인의류
까투리충주
밥묵고가소
F1자동차부분정비공업사
가미오리
달
큰사람컴퓨터
정통
꼬마루
본가할매숨두부
에이스침대，코아스웰
대광농약농자재마트
토트영수학원
은혜미용실2
달콤단백
본어게인
월악파머스캠핑장
하늘광고기획
월드치킨호프
경복궁
산막이옛길협동조합
타투앤뷰티
풍년농자재
금수산장례.철학관
정안인쇄광고기획
원조춘천닭갈비
지에스25청전사거리
대성정보통신
휴먼리스팩트
벡세진건강원
창포헤어클럽
샤론뜨개방
클레오파트라
골드워터생맥주
예성문구사
오드리컴퍼니
행복한맛집
서울칼라
청주광림
청송식당
워시프렌즈셀프빨래방청주더까까주까
청와삼대
서울더바른치과의원
충북고등학교교육경제공동체사회적협동조합
영원클린풀
오케이온진양골프
생거진천라이프
강촌
씨제이미용실
머리하는풍경
센트럴힐데스하임공인중개사사무소
희망건축설비
더끌림스킨앤왁싱
주공할인마트
세븐일레븐충북대포커스점
씨엘
누구라도식당
다올에스테틱
피엠푸드율량
포레니티
어나더스윗
고려기획
한결에너지
커피와향기이야기
샤인덴탈
우정사료할인매장
오가닉메이커협동조합
미래낚시산업
양자강
학천주유소
레미니스펜션
솔잎미용실
에이스공인중개사사무소
헤어마루
작은음악회
BS86본점
리펌헤어
인디안롯데청주점
리베흐테
여기;돈까스
로즈힐영동점
생수앤헬스
일꾼용역
수전자
대흥상회
영진공업사
해피클린
한국자동차공업사주
유엘케이
제일솔루션
영동OA랜드
쉴만한물가
지에스25뉴오창비발디점.1등로또복권
황금셀프
플로르발리오사
서울찹쌀순대
기운쎈장어
아울렛DC마트
엽돈재가든
청주현대갤럭시
블루원푸드
백조종합인테리어
프로실사출력
P텔레콤
원가네시골손두부
여가행사연구소스카이방역소독
마이스위츠팩토리
원라지에터
충주축산업협동조합이용원
양지사주
VIBRA스튜디오
엘에이치조경
칠성공인중개사사무소
샵PC클럽
주성할인마트
인사동밥집
토탈산업건설주
더최선
일신부동산중개사무소
맛찬들3.5왕소금구이
숲골농원
다온인테리어
오창과학산업단지관리공단
카페마리
금복상사
모아찬
엘림종합광고기획
중화식객
굴바위농원
테니스윙아카데미
연승연부동산컨설팅
증평루마썬팅
아띠
프라이빗캠프닉
오갑산주유소
개미돈까스
카페풍경
현대오일뱅크직영학천주유소
부윤세탁소
디팍스청주점
유로코피자
아인스랩
중원부동산공인중개사사무소
뷰티힐링테라피센타
부여상회
테크노비앤에스
언니네미장원
고려식당
이마트24충주예성점
예촌
용산파크
대한췌장담도학회대전충청지회
삼원철물
우성의료기
푸른유통
이끌린헤어
카페디.디청주우암시니어클럽
대신상사
조원전력
단짠테이블
초이스
굿모닝공인중개사사무소
깨끗한청소
수빈헤어뱅크
복대분식
신민경법무사행정사사무소
한우리축산
아테나
레드컴퍼니
뉴그린공인중개사사무소
가전종합서비스
수정설비
기업도시비젼스터디카페24h
전통만두
태화장
태영기획
우리할매떡볶이충북
탑테크엔지니어링
새론동물병원
법무사이명세사무소
미소엘이디
신동아세탁소
계룡리슈빌부동산공인중개사사무소
미사리라이브
궁전떡집
안터식당
아빠청포도
생태숲펜션가든
일미닭갈비파전
에이치에스
하이카플라자
음성프로
신세계파크골프
우리메디칼
상무초밥청주점
보떼리아미용재료
킴스팜
크린토피아청주복대영조점
블럭팡
다옴포차
샤트렌
아메리카신발
대가한방족발
패션몰
와와랜드
땡큐노래연습장
만능중고제품할인매장
덕이칼국수
한국자동차정비공업사
스마일주택관리
신용세탁소
아기동물
원재한약방
우리들기업
헤아
문의세탁소
서진드살롱
조은집
가연인쇄사
백제해장국
오사랑복권
샹하이
아름다운사람들
삼천궁녀노래클럽
씨유음성신천
일품공인중개사사무소
거성부동산개발
오크통바베큐치킨호프
이월마트
옛날할머니보리밥집
성원마늘약선요리
할티선녀탕
한국재능개발연구회사
제니퍼창의융합영어
통나무집펜션
보람노승방공인중개사사무소
명성참숯생고기
옛날전통추어탕
디플레이
디자인백
두존치킨
기배공인중개사
토토미용실
영골드
세일측량설계
재재이야기
달달하쥬
성심장례협동조합
형제모터스
지구철물건재
슬림홀릭피부관리
느린마을양조장술펍
흥부찜닭
이화텔레콤
그랜드가발진헤어
늑대와여우
아트공방
샤넬헤어샵
이팝
나무골건강원
설규푸드
참조자동차공업사
문화빌딩
현대세탁소
삼원이엔지
천등산캠핑장
박서영뷰티컬렉션
버블
대구상회
척산만남의광장
그린에어컨
썸
대성건재
먹거리촌실내포장마차
1865스크린골프
혼밥대장음성대소점
청정돼지국내산삼겹살봉명사창점
현대샷시유리공사
에이치케이산업
대성종합기술단
고래의꿈수족관
행운복권방
라인떡방
만물상회
청전마트
테이블1101
기노스킨
한입두잎
뉴발란스
청실홍실화장품
수레울힐링마을
송재근치과의원
규수방
도쿄이즈미
제이빔
진유도관
태림식당
보약갈비탕
프로광고기획
투어바웃
제천스포츠
금성가든
기업도시공인중개사사무소
법인한방건강인
고려베이커리
혜당생활과학복대지점
골든이용원
투다리칠금점
레이닝골드24시편의점
성신인터내셔날
쌍떼헤어모드
다락라이브
현대오일뱅크직영청주역주유소
순두부짬뽕
미르F&C
헤어아뜰리에
안도리식당
감나무집
문화당구장
라헤어
반도갤러리
나눔
삼성세월
칼슨그레이시오창지부
별별명품구제
우리마트
끌래모아헤어샵
음메꿀꿀사랑이야기
일등공인중개사사무소
원봉푸르넷공부방
챌린저영어학원
학교법인숭희학원
옛날칼국수
제일이용원
브릿지파스타
하나로베이커리
하나로행정사사무소
더플레이그라운드
파크랜드
앙드레
보은전자랜드
무림장
바른주방기기
환요성식당
강변캠핑장
오아시스모텔
이경규의돈치킨능암점
자성화맛집코다리네
지에스25봉산
우리동네카페
매드기어
주덕약국
뷰티비바
쎄시봉노래연습장
그린동물병원
신헤어#
롯데쇼핑롯데슈퍼주
금화공인중개사사무소
두꺼비주유소
또바기
구인공인중개사사무소
광덕철물
에스엘아이평생교육원충북지사
플러스진로상담소
고불고불
장미커텐
1.0안경
뚝방집식당
공간;슬아
에몬스가구
향몽
안창살전문
갈비탕의품격
지산공인중개사사무소
정미관
짝노래연습장
6000냥원컷
위드매쓰
두잇스터디카페청주
청기와감자탕
코리아세븐청주뉴
강변마을
청주에버세이브지이크파렌하이트
과자한바구니
시스터즈
조약돌미용실
단양민물매운탕쏘가리
팔선
교촌치킨
코코
소백산매점
크리스피자&홍탕
미래여성산부인과의원
금강민물매운탕
꽃차덖는집
홍프로짐
아이샵
하프라이브
동서가구청남점
박주윤피부관리.화장품
한섬하우스FX라이브1
서울치과의원
엠커피팩토리
두리메링게주
대호감자탕
아이스크림할인마켓
스타동물병원
대보냉동
보릿고개
정성이엔씨
제로나인
선경엔지니어링
온뮤직연습실
모리노헤어
아우라
대운식당
민금선보컬학원
반야골슈퍼식당
디자인팩토리
민들레슈퍼;문구
씨제이마케팅
남도복집
선물마트
블루페페
Q당구장;큐호프
결혼정보커플
3.33D플레이그라운드
크린골드
미쁘다
이정희
토마토마트정육점
리틀왈츠피아노교습소
남부축산물
에이원테크
모빈관
하예성바이올린음악교습소
한반도컨설팅공인중개사사무소
영클린
와이지컴퍼니나보나
한빛인쇄
판다팜
컴퓨터닥터９１１
이브자리율량사천
믿음치과
대지카센타
SK오창주유소
조이엘아이스크림수곡
이엠피영어수학전문학원
준타운
중앙시장중앙모자
기쁜소리사
청주신한
베스트골프
삼흥종합수도
알찬네찬
아쿠아정수기
진양세차장
육회&딱새우
살리고노래연습장
라온텔레콤
시장다방
도미너스
미미호떡
보듬아동가족통합센터진천
토마토마트생선코너
8000부동산공인중개사중개인합동사무소
현대컴퓨터크리닝
몽땅연필스터디카페청주모충점
리프에스테틱
가곡여울
S모텔
착한중고폰
유진공구철물
청춘반점
다솜골
세븐일레븐청주현도
충북오피스알파문구음성군점
말자싸롱내덕점
대동면옥
록원식당
순신토불이
명동칼국수
대림노래연습장
토정한삼인
가보래한정식
불독
대왕석유무역;서울셀프주유소
용바위골휴게소
별미올갱이
청주제일중개사사무소
뚜레쥬르비하
셀럽
다트호프
강문수정보통신
그린조경개발
올리브나무
샘골매점
신풍식당
루나
하늘아래별천지민박
쿠라이
에이스당구클럽
돌풍식당
우리약국
주제통합독서센터
레이렌탈
두리가
한우한돈
미당라이브
상상블럭청주점
하오인터내셔널
형제주유소
김학근법무사사무소
진흥부동산
복대동주유소
해뜨는집
까사미아충주점
청양회관
다오디자인
전주식당
크린토피아충주칠금부영1차점
NC공인중개사사무소
에스엠빌딩
현머리방
애플베리잉글리쉬청주