In [18]:
import pandas as pd
import re
from konlpy.tag import Okt
from collections import defaultdict
# 데이터 로드
df = pd.read_csv('daum_movie_review.csv')
okt = Okt()
df.head()

,review,rating,date,title
0,돈 들인건 티가 나지만 보는 내내 하품만,1,2018.10.29,인피니티 워
1,몰입할수밖에 없다. 어렵게 생각할 필요없다. 내가 전투에 참여한듯 손에 땀이남.,10,2018.10.26,인피니티 워
2,이전 작품에 비해 더 화려하고 스케일도 커졌지만.... 전국 맛집의 음식들을 한데 ...,8,2018.10.24,인피니티 워
3,이 정도면 볼만하다고 할 수 있음!,8,2018.10.22,인피니티 워
4,재미있다,10,2018.10.20,인피니티 워

In [20]:
# 명사기반 검색엔진 구현(형태소 분석기 응용) - 형태소 분석기를 통해서 조사가 무엇이든간에 핵심의미(명사)

# 역색인 inverted index 
iverted_index = defaultdict(list)
for idx, row in df.head(1000).iterrows():
    review = row['review']
    nouns = okt.nouns(review)
    for noun in set(nouns):
        if len(noun) > 1 :
            iverted_index[noun].append(idx)

def search_movie_review(query):
    '''질의어에서 명사 추출'''
    query_nouns = okt.nouns(query)
    # 첫번째 명사기준으로 검색(단순화)
    target_noun = query_nouns[0]
    if target_noun in iverted_index:
        match_index = iverted_index[target_noun]
        return df.loc[match_index][['review','rating']].head()
    else:
        return '검색 결과가 없습니다.'

search_movie_review('영화가')

                                               review  rating
21  롱턱 타노스의  장갑이 참 맘에 듬.  아이언 맨과 토르 닥터만 생고생하고..  가...       6
26  이 영화를 보고나서 예전 영화 왓치맨이 생각나더군요 평화를 위해선 불특정 다수의 희...       9
34  어벤져스 답게 쏟아붓긴 했는데 한방이 없었다마블 영화들은 보고나면 늘 긴 예고편 본...       5
41  이건 뭐~  이 정도 돈과 출연진 가지고 이렇게 망칠 수도 있구나를 보여주는 대표작...       2
44                                마블 팬이라면 반드시 봐야하는 영화      10